sistemaMercado:
  db:
    strConn: jdbc:postgresql://localhost:5432/mercadoDB
    usr: postgres
    pwd: postgres
    jdbcDriver: org.postgresql.Driver

spring:
  application:
    name: sistema-terminais
  datasource:
      url: ${sistemaMercado.db.strConn}
      username: ${sistemaMercado.db.usr}
      password: ${sistemaMercado.db.pwd}
      driver-class-name: ${sistemaMercado.db.jdbcDriver}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: schemamercado
    locations: classpath:db/migration
    url: ${sistemaMercado.db.strConn}
    user: ${sistemaMercado.db.usr}
    password: ${sistemaMercado.db.pwd}
    mixed: false
  thymeleaf:
      cache: false
  cache:
    type: simple
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    openfeign:
      client:
        default:
          connectTimeout: 60000
          readTimeout: 60000

server:
  port: 8080
  servlet:
    context-path: /api-mercado

# URL da API-TV (ajuste conforme seu ambiente)
api:
  tv:
    host: http://localhost
    port: 8081
    base:
      url: ${api.tv.host}:${api.tv.port}

logging:
  level:
    com.mercado.sistema: DEBUG
    org:
      springframework.security: DEBUG
      springframework.cache: DEBUG
      hibernate.sql: DEBUG

file:
  monitor:
    path_raiz: C:/Users/Junior/Documents/_Cliente_e_Consultorias/atacadao/importacao/input/output
    input-directorio: ${file.monitor.path_raiz}/jsonprodutos
    output-directorio: ${file.monitor.path_raiz}/gravadosAposCarga
    polling-interval: 5000  # milissegundos
    file-pattern: "produtos_*.json"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  server:
    port: ${server.port}